/*
-- Query: SELECT * FROM pokedex.abilities
LIMIT 0, 1000

-- Date: 2023-06-04 22:21
*/
INSERT INTO `` (`id`,`ability`,`description`) VALUES (1,'Stench',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (2,'Drizzle',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (3,'Speed Boost',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (4,'Battle Armor',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (5,'Sturdy',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (6,'Damp',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (7,'Limber',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (8,'Sand Veil',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (9,'Static',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (10,'Volt Absorb',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (11,'Water Absorb',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (12,'Oblivious',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (13,'Cloud Nine',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (14,'Compound Eyes',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (15,'Insomnia',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (16,'Color Charge',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (17,'Immunity',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (18,'Flash Fire',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (19,'Shield Dust',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (20,'Own Tempo',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (21,'Suction Cups',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (22,'Intimidate',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (23,'Shadow Tag',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (24,'Rough Skin',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (25,'Wonder Guard',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (26,'Levitate',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (27,'Effect Spore',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (28,'Synchronize',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (29,'Clear Body',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (30,'Natural Cure',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (31,'Lightning Rod',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (32,'Serene Grace',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (33,'Swift Swim',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (34,'Chlorophyll',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (35,'Illuminate',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (36,'Trace',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (37,'Huge Power',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (38,'Poison Point',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (39,'Inner Focus',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (40,'Magma Armor',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (41,'Water Veil',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (42,'Magnet Pull',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (43,'Soundproof',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (44,'Rain Dish',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (45,'Sand Stream',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (46,'Pressure',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (47,'Thick Fat',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (48,'Early Bird',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (49,'Flame Body',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (50,'Run Away',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (51,'Keen Eye',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (52,'Hyper Cutter',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (53,'Pickup',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (54,'Truant',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (55,'Hustle',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (56,'Cute Charm',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (57,'Plus',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (58,'Minus',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (59,'Forecast',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (60,'Sticky Hold',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (61,'Shed Skin',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (62,'Guts',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (63,'Marvel Scale',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (64,'Liquid Ooze',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (65,'Overgrow',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (66,'Blaze',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (67,'Torrent',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (68,'Swarm',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (69,'Rock Head',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (70,'Drought',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (71,'Arena Trap',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (72,'Vital Spirit',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (73,'White Smoke',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (74,'Pure Power',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (75,'Shell Armor',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (76,'Air Lock',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (77,'Tangled Feet',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (78,'Motor Drive',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (79,'Rivalry',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (80,'Steadfast',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (81,'Snow Cloak',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (82,'Gluttony',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (83,'Anger Point',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (84,'Unburden',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (85,'Heatproof',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (86,'Simple',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (87,'Dry Skin',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (88,'Download',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (89,'Iron Fist',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (90,'Poison Heal',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (91,'Adaptability',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (92,'Skill Link',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (93,'Hydration',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (94,'Solar Power',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (95,'Quick Feet',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (96,'Normalize',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (97,'Sniper',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (98,'Magic Guard',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (99,'No Guard',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (100,'Stall',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (101,'Technician',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (102,'Leaf Guard',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (103,'Klutz',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (104,'Mold Breaker',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (105,'Super Luck',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (106,'Aftermath',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (107,'Anticipation',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (108,'Forewarn',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (109,'Unaware',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (110,'Tinted Lens',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (111,'Filter',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (112,'Slow Start',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (113,'Scrappy',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (114,'Storm Drain',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (115,'Ice Body',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (116,'Solid Rock',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (117,'Snow Warning',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (118,'Honey Gather',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (119,'Frisk',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (120,'Reckless',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (121,'Multitype',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (122,'Flower Gift',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (123,'Bad Dreams',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (124,'Pickpocket',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (125,'Sheer Force',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (126,'Contrary',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (127,'Unnerve',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (128,'Defiant',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (129,'Defeatist',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (130,'Cursed Body',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (131,'Healer',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (132,'Friend Guard',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (133,'Weak Armor',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (134,'Heavy Metal',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (135,'Light Metal',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (136,'Multiscale',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (137,'Toxic Boost',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (138,'Flare Boost',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (139,'Harvest',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (140,'Telepathy',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (141,'Moody',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (142,'Overcoat',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (143,'Poison Touch',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (144,'Regenerator',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (145,'Big Pecks',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (146,'Sand Rush',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (147,'Wonder Skin',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (148,'Analytic',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (149,'Illusion',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (150,'Imposter',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (151,'Infiltrator',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (152,'Mummy',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (153,'Moxie',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (154,'Justified',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (155,'Rattled',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (156,'Magic Bounce',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (157,'Sap Sipper',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (158,'Prankster',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (159,'Sand Force',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (160,'Iron Barbs',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (161,'Zen Mode',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (162,'Victory Star',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (163,'Turboblaze',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (164,'Teravolt',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (165,'Aroma Veil',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (166,'Flower Veil',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (167,'Cheek Pouch',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (168,'Protean',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (169,'Fur Coat',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (170,'Magician',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (171,'Bulletproof',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (172,'Competitive',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (173,'Strong Jaw',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (174,'Refrigerate',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (175,'Sweet Veil',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (176,'Stance Change',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (177,'Gale Wings',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (178,'Mega Launcher',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (179,'Grass Pelt',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (180,'Symbiosis',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (181,'Tough Claws',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (182,'Pixilate',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (183,'Gooey',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (184,'Aerilate',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (185,'Parental Bond',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (186,'Dark Aura',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (187,'Fairy Aura',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (188,'Aura Break',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (189,'Primordial Sea',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (190,'Desolate Land',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (191,'Delta Stream',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (192,'Stamina',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (193,'Wimp Out',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (194,'Emergency Exit',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (195,'Water Compaction',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (196,'Merciless',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (197,'Shields Down',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (198,'Stakeout',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (199,'Water Bubble',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (200,'Steelworker',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (201,'Berserk',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (202,'Slush Rush',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (203,'Long Reach',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (204,'Liquid Voice',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (205,'Triage',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (206,'Galvanize',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (207,'Surge Surfer',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (208,'Schooling',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (209,'Disguise',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (210,'Battle Bond',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (211,'Power Construct',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (212,'Corrosion',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (213,'Comatose',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (214,'Queenly Majesty',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (215,'Innards Out',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (216,'Dancer',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (217,'Battery',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (218,'Fluffy',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (219,'Dazzling',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (220,'Soul-Heart',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (221,'Tangling Hair',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (222,'Receiver',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (223,'Power of Alchemy',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (224,'Beast Boost',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (225,'RKS System',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (226,'Electric Surge',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (227,'Psychic Surge',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (228,'Misty Surge',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (229,'Grassy Surge',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (230,'Full Metal Body',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (231,'Shadow Shield',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (232,'Prism Armor',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (233,'Neuroforce',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (234,'Intrepid Sword',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (235,'Dauntless Shield',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (236,'Libero',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (237,'Ball Fetch',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (238,'Cotton Down',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (239,'Propeller Tail',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (240,'Mirror Armor',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (241,'Gulp Missile',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (242,'Stalwart',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (243,'Steam Engine',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (244,'Punk Rock',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (245,'Sand Spit',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (246,'Ice Scales',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (247,'Ripen',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (248,'Ice Face',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (249,'Power Spot',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (250,'Mimicry',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (251,'Screen Cleaner',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (252,'Steely Spirit',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (253,'Perish Body',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (254,'Wandering Spirit',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (255,'Gorilla Tactics',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (256,'Neutralizing Gas',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (257,'Pastel Veil',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (258,'Hunger Switch',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (259,'Quick Draw',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (260,'Unseen Fist',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (261,'Curious Medicine',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (262,'Transistor',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (263,'Dragons Maw',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (264,'Chilling Neigh',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (265,'Grim Neigh',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (266,'As One',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (267,'As One',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (268,'Lingering Aroma',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (269,'Seed Sower',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (270,'Thermal Exchange',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (271,'Anger Shell',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (272,'Purifying Salt',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (273,'Well-Baked Body',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (274,'Wind Rider',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (275,'Guard Dog',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (276,'Rocky Payload',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (277,'Wind Power',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (278,'Zero to Hero',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (279,'Commander',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (280,'Electromorphosis',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (281,'Protosynthesis',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (282,'Quark Drive',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (283,'Good as Gold',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (284,'Vessel of Ruin',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (285,'Sword of Ruin',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (286,'Tablets of Ruin',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (287,'Beads of Ruin',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (288,'Orichalcum Pulse',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (289,'Hadron Engine',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (290,'Opportunist',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (291,'Cud Chew',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (292,'Sharpness',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (293,'Supreme Overload',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (294,'Costar',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (295,'Toxic Debris',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (296,'Armor Tail',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (297,'Earth Eater',NULL);
INSERT INTO `` (`id`,`ability`,`description`) VALUES (298,'Mycelium Might',NULL);
