/*
-- Query: SELECT * FROM pokedex.moves
LIMIT 0, 1000

-- Date: 2023-06-04 22:00
*/
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (1,'Pound',40,100,35,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (2,'Karate Chop',50,100,25,1,3);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (3,'Double Slap',15,85,10,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (4,'Comet Punch',18,85,15,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (5,'Mega Punch',80,85,20,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (6,'Pay Day',40,100,20,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (7,'Fire Punch',75,100,15,1,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (8,'Ice Punch',75,100,15,1,12);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (9,'Thunder Punch',75,100,15,1,8);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (10,'Scratch',40,100,35,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (11,'Vise Grip',55,100,30,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (12,'Guillotine',0,30,5,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (13,'Razor Wind',80,100,10,2,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (14,'Swords Dance',0,0,20,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (15,'Cut',50,95,30,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (16,'Gust',40,100,35,2,5);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (17,'Wing Attack',60,100,35,1,5);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (18,'Whirlwind',0,0,20,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (19,'Fly',90,95,15,1,5);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (20,'Bind',15,85,20,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (21,'Slam',80,75,20,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (22,'Vine Whip',45,100,25,1,6);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (23,'Stomp',65,100,20,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (24,'Double Kick',30,100,30,1,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (25,'Mega Kick',120,75,5,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (26,'Jump Kick',100,95,10,1,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (27,'Rolling Kick',60,85,15,1,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (28,'Sand Attack',0,100,15,3,9);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (29,'Headbutt',70,100,15,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (30,'Horn Attack',65,100,25,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (31,'Fury Attack',15,85,20,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (32,'Horn Drill',0,30,5,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (33,'Tackle',40,100,35,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (34,'Body Slam',85,100,15,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (35,'Wrap',15,90,20,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (36,'Take Down',90,85,20,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (37,'Thrash',120,100,10,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (38,'Double-Edge',120,100,15,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (39,'Tail Whip',0,100,30,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (40,'Poison Sting',15,100,35,1,7);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (41,'Twineedle',25,100,20,1,13);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (42,'Pin Missile',25,95,20,1,13);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (43,'Leer',0,100,30,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (44,'Bite',60,100,25,1,16);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (45,'Growl',0,100,40,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (46,'Roar',0,0,20,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (47,'Sing',0,55,15,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (48,'Supersonic',0,55,20,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (49,'Sonic Boom',0,90,20,2,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (50,'Disable',0,100,20,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (51,'Acid',40,100,30,2,7);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (52,'Ember',40,100,25,2,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (53,'Flamethrower',90,100,15,2,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (54,'Mist',0,0,30,3,12);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (55,'Water Gun',40,100,25,2,4);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (56,'Hydro Pump',110,80,5,2,4);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (57,'Surf',90,100,15,2,4);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (58,'Ice Beam',90,100,10,2,12);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (59,'Blizzard',110,70,5,2,12);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (60,'Psybeam',65,100,20,2,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (61,'Bubble Beam',65,100,20,2,4);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (62,'Aurora Beam',65,100,20,2,12);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (63,'Hyper Beam',150,90,5,2,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (64,'Peck',35,100,35,1,5);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (65,'Drill Peck',80,100,20,1,5);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (66,'Submission',80,80,20,1,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (67,'Low Kick',0,100,20,1,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (68,'Counter',0,100,20,1,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (69,'Seismic Toss',0,100,20,1,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (70,'Strength',80,100,15,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (71,'Absorb',20,100,25,2,6);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (72,'Mega Drain',40,100,15,2,6);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (73,'Leech Seed',0,90,10,3,6);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (74,'Growth',0,0,20,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (75,'Razor Leaf',55,95,25,1,6);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (76,'Solar Beam',120,100,10,2,6);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (77,'Poison Powder',0,75,35,3,7);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (78,'Stun Spore',0,75,30,3,6);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (79,'Sleep Powder',0,75,15,3,6);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (80,'Petal Dance',120,100,10,2,6);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (81,'String Shot',0,95,40,3,13);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (82,'Dragon Rage',0,100,10,2,14);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (83,'Fire Spin',35,85,15,2,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (84,'Thunder Shock',40,100,30,2,8);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (85,'Thunderbolt',90,100,15,2,8);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (86,'Thunder Wave',0,90,20,3,8);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (87,'Thunder',110,70,10,2,8);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (88,'Rock Throw',50,90,15,1,11);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (89,'Earthquake',100,100,10,1,9);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (90,'Fissure',0,30,5,1,9);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (91,'Dig',80,100,10,1,9);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (92,'Toxic',0,90,10,3,7);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (93,'Confusion',50,100,25,2,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (94,'Psychic',90,100,10,2,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (95,'Hypnosis',0,60,20,3,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (96,'Meditate',0,0,40,3,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (97,'Agility',0,0,30,3,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (98,'Quick Attack',40,100,30,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (99,'Rage',20,100,20,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (100,'Teleport',0,0,20,3,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (101,'Night Shade',0,100,15,2,15);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (102,'Mimic',0,0,10,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (103,'Screech',0,85,40,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (104,'Double Team',0,0,15,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (105,'Recover',0,0,10,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (106,'Harden',0,0,30,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (107,'Minimize',0,0,10,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (108,'Smokescreen',0,100,20,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (109,'Confuse Ray',0,100,10,3,15);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (110,'Withdraw',0,0,40,3,4);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (111,'Defense Curl',0,0,40,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (112,'Barrier',0,0,20,3,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (113,'Light Screen',0,0,30,3,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (114,'Haze',0,0,30,3,12);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (115,'Reflect',0,0,20,3,10);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (116,'Focus Energy',0,0,30,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (117,'Bide',0,0,10,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (118,'Metronome',0,0,10,3,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (119,'Mirror Move',0,0,20,3,5);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (120,'Self-Destruct',200,100,5,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (121,'Egg Bomb',100,75,10,1,1);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (122,'Lick',30,100,30,1,15);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (123,'Smog',30,70,20,2,7);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (124,'Sludge',65,100,20,2,7);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (125,'Bone Club',65,85,20,1,9);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (126,'Fire Blast',110,85,5,2,2);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (127,'Waterfall',80,100,15,1,4);
INSERT INTO `moves` (`id`,`move`,`power`,`accuracy`,`pp`,`move_type_id`,`pkm_type_id`) VALUES (128,'Clamp',35,85,15,1,4);
